[package]
name = "seichi-ranking-bff"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.1.0", features = ["rustls"] }
anyhow = "1.0.61"
async-lock = "2.5.0"
async-trait = "0.1.57"
chrono = { version = "0.4.22", features = ["serde"] }
envy = "0.4.2"
fern = { version = "0.6.1", features = ["colored"] }
log = "0.4.17"
once_cell = "1.13.0"
qstring = "0.7.2"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.20.1", features = ["macros"] }
uuid = { version = "1.1.2", features = ["serde"] }
